# Generated by Django 4.2.13 on 2024-07-12 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_alter_product_image"),
        ("base", "0006_alter_product_image_alter_product_price"),
    ]

    operations = []
